"""
pdf_engine.py — LLM-powered PDF generator using WeasyPrint.

Replaces xhtml2pdf. Uses WeasyPrint for full CSS3 support and correct ₹ rendering.
Domain-agnostic. Works for any industry via doc_type hints + pre-processed rows.
"""
import json
import os
from io import BytesIO
from datetime import datetime
from openai import AsyncOpenAI

_client = AsyncOpenAI(api_key=os.getenv("OPENAI_API_KEY"))

BRAND_BLUE   = "#185FA5"
BRAND_LIGHT  = "#EEF4FB"
BRAND_DARK   = "#1A1A2E"
BRAND_MUTED  = "#6B7280"

# Risk colours (used in prompts and potentially in generated HTML)
RISK_COLORS = {
    "HIGH":     {"bg": "#B71C1C", "row": "#FFEBEE", "text": "#FFFFFF"},
    "MEDIUM":   {"bg": "#E65100", "row": "#FFF3E0", "text": "#FFFFFF"},
    "LOW":      {"bg": "#2E7D32", "row": "#F1F8E9", "text": "#FFFFFF"},
    "UPCOMING": {"bg": "#1565C0", "row": "#E3F2FD", "text": "#FFFFFF"},
}


async def generate_pdf(
    rows: list,
    title: str,
    org_name: str,
    subtitle: str = "",
    doc_type: str = "report",
    extra_context: dict = None,
) -> bytes:
    """Generate a professional A4 PDF. Returns bytes. Raises on error."""
    html = await _build_html(
        rows=rows,
        title=title,
        org_name=org_name,
        subtitle=subtitle,
        doc_type=doc_type,
        extra_context=extra_context or {},
    )
    return _html_to_pdf(html)


async def _build_html(rows, title, org_name, subtitle, doc_type, extra_context) -> str:
    today      = datetime.now().strftime("%d %b %Y")
    today_long = datetime.now().strftime("%d %B %Y")

    data_for_prompt = rows[:100]
    truncated = len(rows) > 100
    data_json = json.dumps(data_for_prompt, default=str, indent=2)
    ctx_json  = json.dumps(extra_context,   default=str, indent=2)
    trunc_note = (
        f"\n(Note: showing first 100 of {len(rows)} rows)"
        if truncated else ""
    )

    # Detect if this is an aging report — enables colour-bucketed rendering
    has_risk_buckets = any("risk_bucket" in r for r in data_for_prompt)
    has_days_overdue = any("days_overdue" in r for r in data_for_prompt)
    # doc_type="invoice" and "quotation" are NEVER rendered as aging reports,
    # even if the preprocessor somehow tagged their rows.
    risk_mode = (has_risk_buckets or has_days_overdue) and doc_type not in ("invoice", "quotation")

    prompt = f"""You are generating a professional PDF document for a business using WeasyPrint.
WeasyPrint supports full CSS3 including flexbox, CSS variables, border-radius, and proper Unicode.

===== DOCUMENT DETAILS =====
Organization  : {org_name}
Document Type : {doc_type}
Title         : {title}
Subtitle      : {subtitle or "(none)"}
Date          : {today_long}
Total Rows    : {len(rows)}{trunc_note}
Has Risk Buckets : {risk_mode}

===== DATA =====
{data_json}

===== PRE-COMPUTED CONTEXT =====
(Use these values directly. Do NOT recalculate from the rows above.)
{ctx_json}

===== FONTS AND COLORS =====
Use this CSS at the top of <head>:
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
  /* Fallback stack that includes Noto Sans for ₹ symbol: */
  body {{ font-family: 'Inter', 'Noto Sans', 'DejaVu Sans', Arial, sans-serif; font-size: 11pt; color: {BRAND_DARK}; }}
  @page {{ size: A4; margin: 12mm 15mm 15mm 15mm; }}
</style>

Primary blue  : {BRAND_BLUE}
Light blue bg : {BRAND_LIGHT}
Dark text     : {BRAND_DARK}
Muted text    : {BRAND_MUTED}

CRITICAL — Use ONLY "Rs." for currency, NOT the ₹ symbol.
Write: Rs.1,45,000  NOT: ₹1,45,000
The Rupee symbol breaks in some rendering environments. "Rs." is universal.

===== ALWAYS INCLUDE (every doc type) =====
1. HEADER BLOCK (table-based, full width):
   Left cell:  org name in bold {BRAND_BLUE} 18pt | document type label 11pt muted
   Right cell: date right-aligned | subtitle if provided

2. Thin horizontal rule (<hr style="border:2px solid {BRAND_BLUE}; margin:8px 0">) below header

3. FOOTER (bottom of page, small, muted):
   "Generated by OrchestrAI on {today}"

===== DOC-TYPE SPECIFIC INSTRUCTIONS =====

{"" if not risk_mode else f"""
── AGING REPORT (risk_bucket data detected) ──

The rows already have `risk_bucket` (HIGH / MEDIUM / LOW / UPCOMING) and
`days_overdue` pre-computed. Use this to render THREE colour-coded sections.

STRUCTURE:
1. EXECUTIVE SUMMARY BOX (light blue bg, rounded corners, 8px padding):
   Show grand_total, high_risk_total, medium_risk_total from extra_context.
   If top_debtors in extra_context, list them here.
   Format: "Total Outstanding: Rs.X | High Risk: Rs.X | Medium Risk: Rs.X"

2. THREE SECTION BLOCKS (render only non-empty buckets):

   HIGH RISK — Over 90 Days
   Header row bg: #B71C1C, white text, bold
   Data rows bg: #FFEBEE (light red)
   Show: Invoice # | Customer | Amount | Days Overdue | Status

   MEDIUM RISK — 31 to 90 Days
   Header row bg: #E65100, white text, bold
   Data rows bg: #FFF3E0 (light orange)

   LOW RISK — Up to 30 Days
   Header row bg: #2E7D32, white text, bold
   Data rows bg: #F1F8E9 (light green)

   UPCOMING — Not Yet Due
   Header row bg: {BRAND_BLUE}, white text, bold
   Data rows bg: {BRAND_LIGHT}

   Each section heading ABOVE the table (full-width div):
   <div style="background:#B71C1C;color:#fff;padding:6px 10px;font-weight:700;margin-top:12px;font-size:11pt">
     HIGH RISK — Over 90 Days ({"{"}count{"}"} invoices, Rs.{"{"}total{"}"})
   </div>
   Followed immediately by the table for that bucket.

3. KEY ACTIONS SECTION (below all tables):
   Heading: "Key Actions" in {BRAND_BLUE} bold
   Bullet list of 3-5 specific, actionable items based on the data.
   Examples: "Singh Bullion Mart: Rs.X overdue 120+ days — immediate follow-up needed"
   Make these SPECIFIC to the actual data, not generic placeholders.
   Use the top_debtors from extra_context if available.
"""}

{"" if risk_mode else {
"report": """
── REPORT (multi-row table) ──
- Blue header row (#185FA5, white text), alternating row stripes (white / #EEF4FB)
- All numeric amount/total columns: right-align, Indian comma formatting (Rs.X,XX,XXX)
- Summary row at bottom (bold, light blue bg): row count + SUM of any amount/total column
- KEY INSIGHTS section: 2-4 bullet points synthesising notable patterns in the data
  e.g. "4 items below reorder level" / "3 customers account for 70% of outstanding"
""",
"invoice": """
── TAX INVOICE ──
- TOP RIGHT badge: <div style="background:{BRAND_BLUE};color:#fff;padding:4px 12px;font-weight:700;display:inline-block">TAX INVOICE</div>
- BILL TO section (left): customer_name, city, GSTIN from extra_context
- Invoice meta (right): Invoice #, Date, Due Date, STATUS from extra_context
  Status badge: <div style="background:#16a34a;color:#fff;padding:4px 12px;font-weight:700;display:inline-block">PAID</div> for "paid"
               <div style="background:#dc2626;color:#fff;padding:4px 12px;font-weight:700;display:inline-block">OVERDUE</div> for "overdue"
               <div style="background:#f59e0b;color:#fff;padding:4px 12px;font-weight:700;display:inline-block">PENDING</div> for "pending"
- Items table: Description | Qty | Unit Price (ex-GST) | GST % | Total
- Totals block (right-align, 40% width):
    Subtotal  : use subtotal from extra_context if present; else = amount / 1.03 rounded
    GST (X%)  : use gst_amount from extra_context if present; else = amount - subtotal
    TOTAL     : use total_amount from extra_context if present; else = amount (as-is)
    CRITICAL: NEVER add GST on top of `amount`. `amount` is the GST-INCLUSIVE total.
              If extra_context has subtotal + gst_amount + total_amount, use those directly.
              The "Total in words" must match TOTAL, not Subtotal.
- TOTAL in words (Indian number system): "Rupees One Lakh Forty-Five Thousand Only"
- Payment terms: "Payment due within 30 days. Late payment: 2% per month."
""",
"quotation": f"""
── PRICE QUOTATION — DISTINCT FORMAT (NOT an invoice, use GOLD/AMBER colour scheme) ──

COLOUR SCHEME FOR THIS DOCUMENT ONLY:
  Primary:    #B8860B  (dark gold)
  Light bg:   #FFFBEB  (warm cream)
  Accent:     #C9A84C  (medium gold)
  Text dark:  #3B2800  (dark brown)

HEADER OVERRIDE: Change the header rule colour to #B8860B (not the usual blue).
Change org name colour to #B8860B. Sub-label: "Price Quotation"

BADGE (top right, PROMINENT):
  <div style="background:#B8860B;color:#fff;padding:6px 20px;font-weight:700;
              font-size:13pt;letter-spacing:1px;display:inline-block">
    PRICE QUOTATION
  </div>

DOCUMENT META (two-column table after badge, full width):
  Left col (40%):   "PREPARED FOR:" heading, then customer_name (bold 13pt),
                    city, GSTIN (muted 10pt)
  Right col (60%):  Quote # from extra_context['quotation_number'] (bold)
                    Date: {today_long}
                    Valid Until: extra_context.get('valid_until') (in RED bold if within 2 days)
                    "Valid for {extra_context.get('valid_days', 3)} days only"

DESIGN DETAILS CARD:
  Full-width box, background #FFFBEB, border 2px solid #C9A84C, border-radius 8px, padding 12px:
  Heading "DESIGN DETAILS" in #B8860B bold 11pt.
  Two-column table INSIDE the box:
    Left:  Design Code : extra_context['design_code'] (monospace, bold)
           Design Name : extra_context['design_name'] (bold)
    Right: Metal Type  : extra_context['metal_type']
           Weight      : extra_context['weight_grams'] g

PRICING BREAKDOWN TABLE (right-aligned, width 55%, margin-left auto):
  Border: 1px solid #C9A84C. No zebra stripes. Clean lines.

  Row 1: "Metal Cost"      | "Rs.X,XX,XXX"   (extra_context['metal_cost'])
  Row 2: "Making Charges"  | "Rs.X,XX,XXX"   (extra_context['making_charges'])
         sub-note: "(extra_context['making_charge_pct']% of metal cost)" in muted 9pt
  Divider: thin line
  Row 3: "Subtotal"        | "Rs.X,XX,XXX"   (extra_context['subtotal'])
  Row 4: "GST (X%)"        | "Rs.X,XX,XXX"   (extra_context['gst_pct'] + extra_context['gst_amount'])
  TOTAL ROW (bold, background:#B8860B, color:#fff, font-size:13pt):
           "TOTAL AMOUNT"   | "Rs.X,XX,XXX"  (extra_context['total_amount'])

  ALL values come from extra_context. Do NOT recalculate.
  Use Indian comma formatting for ALL amounts: Rs.1,45,000 not Rs.145000.

VALIDITY BOX:
  Full-width div, background:#FFF3CD (amber warning bg), border-left: 4px solid #B8860B:
  "⚠️  This quotation is valid for {extra_context.get('valid_days', 3)} days from date of issue.
   Gold rates are subject to market fluctuation. Quoted price may vary on actual date of delivery."

TERMS & CONDITIONS (10pt muted):
  • Advance payment required to confirm order.
  • Final weight may vary ±5% from estimate.
  • Making charges are fixed at time of confirmation.
  • GST as per prevailing government rates.

ACCEPTANCE SECTION:
  Two-column table at bottom:
    Left:  "Customer Signature: _____________________"
           "Date: _____________________"
    Right: "For {org_name}"
           "Authorised Signatory: _____________________"

FOOTER NOTE (red, small):
  "This is a QUOTATION, not a Tax Invoice. No tax credit can be claimed against this document."
""",
"statement": """
── DUES / ACCOUNT STATEMENT ──
- Heading: ACCOUNT STATEMENT (bold, large)
- Customer block: name, city, GSTIN, total_outstanding from extra_context
- Outstanding summary: Total Outstanding | Overdue Amount | Invoice Count
- Invoices table with colour-coded rows:
    overdue  → light red  (#FFEBEE)
    pending  → light yellow (#FFFBE6)
  Columns: Invoice # | Date | Due Date | Amount | Status | Days Overdue
- AGING ANALYSIS box (if dates available):
    0–30 days : Rs.X
    31–90 days: Rs.X
    >90 days  : Rs.X  ← flag as HIGH RISK
- Terms: "Please clear outstanding at the earliest. Late interest: 2% per month."
""",
"orders": """
── PRODUCTION ORDERS ──
- Orders table: Order # | Customer | Description | Metal | Status | Est. Amount
- STATUS column coloured cells:
    confirmed     → #E3F2FD (light blue)
    in_production → #FFF8E1 (light amber)
    quality_check → #F3E5F5 (light purple)
    ready         → #E8F5E9 (light green) ← HIGHLIGHT BOLDLY
    delivered     → #F5F5F5 (grey)
- Status emoji legend in footer
- Summary row: total orders, count by status
"""
}.get(doc_type, """
── GENERIC REPORT ──
Clean table with blue header, alternating stripes, summary row.
""")}

===== WEASYPRINT COMPATIBILITY (follow exactly) =====
- Use table-based layouts for multi-column sections — NO CSS float
- Set width="100%" on all tables + explicit column widths with style="width:X%"
- Do NOT use: position:fixed, position:absolute, transform, animation, CSS variables (--name)
- DO use: flexbox is OK in WeasyPrint, border-radius, box-shadow, CSS calc()
- Use <br/> not <br>
- Font sizes: prefer pt units (10pt, 11pt, 12pt, 14pt)
- Page break: style="page-break-before:always" on elements

===== OUTPUT FORMAT =====
Return ONLY the complete HTML starting with <!DOCTYPE html>.
No markdown fences. No explanation. No preamble.
"""

    response = await _client.chat.completions.create(
        model="gpt-4o",
        max_tokens=4096,
        temperature=0.1,
        messages=[{"role": "user", "content": prompt}]
    )

    html = response.choices[0].message.content.strip()
    # Strip any accidental markdown fences
    if html.startswith("```"):
        lines = html.split("\n")
        start = 1 if lines[0].startswith("```") else 0
        end   = len(lines) - 1 if lines[-1].strip() == "```" else len(lines)
        html  = "\n".join(lines[start:end]).strip()

    return html


def _html_to_pdf(html: str) -> bytes:
    """WeasyPrint: HTML string → PDF bytes. Raises ValueError on failure."""
    from weasyprint import HTML
    try:
        buf = BytesIO()
        HTML(string=html).write_pdf(buf)
        return buf.getvalue()
    except Exception as e:
        raise ValueError(f"WeasyPrint conversion failed: {e}")
