"""
pdf_engine.py — Universal LLM-powered PDF generator.

Completely domain-agnostic. Replaces:
  - generate_invoice_pdf()
  - generate_dues_statement_pdf()
  - generate_quotation_pdf()
  - _generate_generic_pdf()

How it works:
  1. Caller passes: data rows + document title + doc_type hint + extra computed context
  2. LLM generates professional A4 HTML for the document
  3. xhtml2pdf converts HTML → PDF bytes
  4. Bytes returned to caller for WhatsApp delivery

Works for jewellery, pharma, IT, hospitals — no code changes per client.
The LLM knows what each document type should look like from its training.
"""
import json
import os
from io import BytesIO
from datetime import datetime
from openai import AsyncOpenAI

_client = AsyncOpenAI(api_key=os.getenv("OPENAI_API_KEY"))


# ── Brand colours (used in the prompt so LLM includes them in HTML) ──────────
BRAND_BLUE  = "#185FA5"
BRAND_LIGHT = "#EEF4FB"
BRAND_DARK  = "#1A1A2E"
BRAND_MUTED = "#6B7280"


async def generate_pdf(
    rows: list,
    title: str,
    org_name: str,
    subtitle: str = "",
    doc_type: str = "report",
    extra_context: dict = None,
) -> bytes:
    """
    Generate a professional PDF from any data.

    Parameters
    ----------
    rows         : list of dicts — the data to show in the document.
                   Can be empty if all data is in extra_context (e.g. quotations).
    title        : str — shown at the top of the PDF (e.g. "Tax Invoice INV-001")
    org_name     : str — company name in the header
    subtitle     : str — optional secondary title or date range
    doc_type     : str — hint for the LLM. One of:
                   "report"     → general data table with summary row
                   "invoice"    → tax invoice with GST breakdown, BILL TO section
                   "quotation"  → price quotation with item details, price breakdown
                   "statement"  → dues/account statement with aging analysis
                   "orders"     → production order list with status indicators
    extra_context: dict — pre-computed values the LLM needs but are not in rows.
                   For invoices: invoice_number, customer details, due_date, gst_rate
                   For quotations: full calculation breakdown (metal_cost, making, gst, total)
                   For statements: total_outstanding, overdue_total, customer details
                   For reports: optional summary totals

    Returns
    -------
    bytes — PDF file contents. Raise on error.
    """
    html = await _build_html(
        rows=rows,
        title=title,
        org_name=org_name,
        subtitle=subtitle,
        doc_type=doc_type,
        extra_context=extra_context or {},
    )
    return _html_to_pdf(html)


async def _build_html(
    rows: list,
    title: str,
    org_name: str,
    subtitle: str,
    doc_type: str,
    extra_context: dict,
) -> str:
    """Call the LLM to generate professional A4 HTML for this document."""
    today = datetime.now().strftime("%d %b %Y")

    # Limit rows to 100 for the prompt (large datasets would overflow token limit)
    data_for_prompt = rows[:100]
    truncated = len(rows) > 100
    data_json = json.dumps(data_for_prompt, default=str, indent=2)
    context_json = json.dumps(extra_context, default=str, indent=2)

    truncation_note = (
        f"\n(Note: data truncated to first 100 of {len(rows)} rows for brevity)"
        if truncated else ""
    )

    prompt = f"""You are generating a professional PDF document for a business.

===== DOCUMENT DETAILS =====
Organization: {org_name}
Document Type: {doc_type}
Title: {title}
Subtitle: {subtitle or "(none)"}
Date: {today}
Total Rows: {len(rows)}{truncation_note}

===== DATA =====
{data_json}

===== PRE-COMPUTED CONTEXT =====
(Use these values directly — do not recalculate from the data above)
{context_json}

===== WHAT TO GENERATE =====
Write a complete, professional A4 HTML document for PDF conversion using xhtml2pdf.

DESIGN:
- Primary blue: {BRAND_BLUE}
- Light blue bg: {BRAND_LIGHT}
- Dark text: {BRAND_DARK}
- Muted text: {BRAND_MUTED}
- Font: Arial, Helvetica, sans-serif
- Page: A4 (210mm × 297mm), margins 15mm

STRUCTURE (always include):
1. Header: org name (large, blue) | document title (medium) | date (right-aligned)
   — Blue divider line beneath header
2. Document body: appropriate for doc_type (see rules below)
3. Footer: "Generated by OrchestrAI on {today}" in muted small text

DOC_TYPE RULES:

report:
  - Data in a clean table with blue header row (white text), alternating light-blue rows
  - Column headers derived from dict keys (convert underscores to spaces, Title Case)
  - Summary row at bottom: count of rows + SUM of any numeric "amount"/"total" columns
  - Add KEY INSIGHTS section below table if data shows notable patterns
    (e.g., "3 items below reorder level — urgent restocking needed")

invoice:
  - "TAX INVOICE" badge in header (right side, blue fill, white text)
  - "BILL TO" section with customer name, city, GSTIN from extra_context
  - Invoice #, Date, Due Date in upper right (from extra_context)
  - Items table: Description | Qty | Unit Price | GST% | Total
  - Totals block (right-aligned): Subtotal, GST amount, TOTAL (blue highlight)
  - Amount in words (Indian system: Rupees X Lakh Y Thousand Only)
  - Terms: "Payment due within 30 days. Late payment: 2% per month."

quotation:
  - "QUOTATION" badge in header
  - "PREPARED FOR" section with customer name and city from extra_context
  - Item Details box (light-blue bg): Metal Type | Weight | Rate per gram | Making%
  - Price Breakdown table:
      Metal Cost = weight × rate_per_gram
      Making Charges = metal_cost × making_charge_pct / 100
      Subtotal
      GST = subtotal × gst_pct / 100
      TOTAL (blue highlight row)
  - All values from extra_context — use them directly, do not recalculate
  - "Quotation valid for 3 days from date of issue" note
  - Terms: Gold rates subject to market fluctuation. Advance required to confirm.

statement:
  - "ACCOUNT STATEMENT" heading
  - Customer details from extra_context (name, city, GSTIN)
  - Outstanding summary box:
      Total Outstanding: ₹X (from extra_context.total_outstanding)
      Overdue Amount: ₹X (from extra_context.overdue_total)
  - Invoice table: Invoice # | Date | Due Date | Amount | Status | Days Overdue
    Colour-code status: overdue rows → light red (#FFF0F0), pending → light yellow (#FFFBE6)
  - Aging analysis if dates available:
      0–30 days: ₹X
      31–90 days: ₹X
      >90 days: ₹X (HIGH RISK)
  - Terms: "Please clear outstanding at the earliest. Late interest: 2% per month."

orders:
  - Orders table with: Order # | Customer | Description | Metal | Status | Est. Amount
  - Status column with emoji indicators:
      confirmed → ✅ Confirmed
      in_production → 🔨 In Production
      quality_check → 🔍 Quality Check
      ready → 📦 Ready for Delivery
      delivered → ✅ Delivered
  - Summary: count by status at the bottom

MONETARY FORMATTING:
  - Always format with ₹ and Indian commas: ₹1,07,000 (not $107,000)
  - Round to nearest rupee for display

XHTML2PDF COMPATIBILITY (critical — follow these or the PDF will break):
  - Use only inline CSS or <style> inside <head> — no external stylesheets
  - Tables: always set width="100%" and explicit column widths via style="width:X%"
  - Use table-based layouts for multi-column sections (no flexbox, no grid, no float)
  - Use <br/> not <br>
  - Do not use CSS variables (--var-name) — use literal hex values
  - Do not use: position:fixed, position:absolute, transform, animation
  - Font sizes in pt preferred (e.g., 10pt, 12pt, 14pt)
  - Page break hints: use style="page-break-before:always" on elements

Return ONLY the complete HTML. Start with <!DOCTYPE html>. No markdown, no code fences, no explanation."""

    response = await _client.chat.completions.create(
        model="gpt-4o",
        max_tokens=4096,
        temperature=0.1,
        messages=[{"role": "user", "content": prompt}]
    )

    html = response.choices[0].message.content.strip()

    # Strip any markdown fences if LLM accidentally adds them
    if html.startswith("```"):
        lines = html.split("\n")
        start = 1 if lines[0].startswith("```") else 0
        end = len(lines) - 1 if lines[-1] == "```" else len(lines)
        html = "\n".join(lines[start:end])
    html = html.strip()

    return html


def _html_to_pdf(html: str) -> bytes:
    """
    Convert HTML string → PDF bytes using xhtml2pdf.
    Raises ValueError if conversion fails.
    """
    from xhtml2pdf import pisa

    buf = BytesIO()
    status = pisa.CreatePDF(html, dest=buf, encoding="utf-8")

    if status.err:
        raise ValueError(
            f"xhtml2pdf conversion failed with {status.err} error(s). "
            f"Check HTML output for malformed tags."
        )

    return buf.getvalue()
