"""
Generates professional invoice PDFs using fpdf2.
Returns PDF as bytes — no file saved to disk.
"""
from fpdf import FPDF
from datetime import datetime


class InvoicePDF(FPDF):
    def header(self):
        # Company name
        self.set_font("Helvetica", "B", 20)
        self.set_text_color(26, 26, 46)
        self.cell(0, 12, "ShreeJewels Pvt Ltd", align="L")
        self.ln(6)
        self.set_font("Helvetica", "", 9)
        self.set_text_color(120, 120, 120)
        self.cell(0, 5, "Automate With AI | Powered by OrchestrAI", align="L")
        self.ln(10)
        # Divider
        self.set_draw_color(74, 0, 224)
        self.set_line_width(0.8)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(6)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, "Generated by OrchestrAI · This is a computer-generated invoice.", align="C")


def generate_invoice_pdf(
    invoice_number: str,
    customer_name: str,
    amount: float,
    items: list = None,
    org_name: str = "ShreeJewels Pvt Ltd"
) -> bytes:
    """
    Generate invoice PDF and return as bytes.
    items = [{"description": "...", "qty": 1, "unit_price": 0, "total": 0}]
    """
    pdf = InvoicePDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # ── Invoice Title ──
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(74, 0, 224)
    pdf.cell(0, 10, "TAX INVOICE", align="R")
    pdf.ln(4)

    # ── Invoice Meta ──
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(50, 50, 50)
    today = datetime.now().strftime("%d %B %Y")
    pdf.cell(0, 6, f"Invoice No: {invoice_number}", align="R")
    pdf.ln(5)
    pdf.cell(0, 6, f"Date: {today}", align="R")
    pdf.ln(10)

    # ── Bill To ──
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 6, "BILL TO", align="L")
    pdf.ln(5)
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(26, 26, 46)
    pdf.cell(0, 7, customer_name, align="L")
    pdf.ln(12)

    # ── Items Table Header ──
    pdf.set_fill_color(74, 0, 224)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(90, 9, "Description", fill=True, align="L", border=0)
    pdf.cell(25, 9, "Qty", fill=True, align="C", border=0)
    pdf.cell(35, 9, "Unit Price", fill=True, align="R", border=0)
    pdf.cell(35, 9, "Total", fill=True, align="R", border=0)
    pdf.ln(9)

    # ── Items ──
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(50, 50, 50)

    if not items:
        items = [{"description": "As per order", "qty": 1, "unit_price": amount, "total": amount}]

    fill = False
    for item in items:
        pdf.set_fill_color(245, 245, 255) if fill else pdf.set_fill_color(255, 255, 255)
        desc = str(item.get("description", "Item"))[:50]
        qty  = str(item.get("qty", 1))
        up   = f"Rs.{float(item.get('unit_price', 0)):,.0f}"
        tot  = f"Rs.{float(item.get('total', amount)):,.0f}"

        pdf.cell(90, 8, desc, fill=True, align="L", border=0)
        pdf.cell(25, 8, qty, fill=True, align="C", border=0)
        pdf.cell(35, 8, up, fill=True, align="R", border=0)
        pdf.cell(35, 8, tot, fill=True, align="R", border=0)
        pdf.ln(8)
        fill = not fill

    pdf.ln(4)

    # ── Divider ──
    pdf.set_draw_color(200, 200, 200)
    pdf.set_line_width(0.3)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)

    # ── Total ──
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(74, 0, 224)
    pdf.cell(150, 9, "TOTAL AMOUNT", align="R")
    pdf.cell(35, 9, f"Rs.{amount:,.0f}", align="R")
    pdf.ln(12)

    # ── Footer Note ──
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 6, "Thank you for your business. Payment due within 30 days.", align="L")
    pdf.ln(4)
    pdf.cell(0, 6, "For queries: sales@aitamate.com", align="L")

    return bytes(pdf.output())
