"""
OrchestrAI — Professional Quotation PDF Generator
Separate from invoice PDF — quotation has validity, breakdown, and terms.
"""
from fpdf import FPDF
from datetime import datetime, timedelta

BLUE    = (24, 95, 165)
DARKTEXT= (26, 26, 46)
MUTED   = (100, 100, 120)
LIGHTBG = (240, 245, 255)
WHITE   = (255, 255, 255)
BORDER  = (220, 228, 240)
GREEN   = (22, 163, 74)


def _amount_in_words(amount: float) -> str:
    ones = ['', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven',
            'Eight', 'Nine', 'Ten', 'Eleven', 'Twelve', 'Thirteen',
            'Fourteen', 'Fifteen', 'Sixteen', 'Seventeen', 'Eighteen', 'Nineteen']
    tens = ['', '', 'Twenty', 'Thirty', 'Forty', 'Fifty',
            'Sixty', 'Seventy', 'Eighty', 'Ninety']

    def two(n):
        if n < 20: return ones[n]
        return tens[n//10] + ((' ' + ones[n%10]) if n%10 else '')

    def three(n):
        if n >= 100:
            return ones[n//100] + ' Hundred' + ((' ' + two(n%100)) if n%100 else '')
        return two(n)

    n = int(amount)
    if n == 0: return 'Zero Only'
    result = ''
    if n >= 10000000:
        result += three(n//10000000) + ' Crore '
        n %= 10000000
    if n >= 100000:
        result += three(n//100000) + ' Lakh '
        n %= 100000
    if n >= 1000:
        result += two(n//1000) + ' Thousand '
        n %= 1000
    if n > 0:
        result += three(n)
    return 'Rupees ' + result.strip() + ' Only'


class QuotationPDF(FPDF):
    def header(self): pass
    def footer(self):
        self.set_y(-12)
        self.set_font('Helvetica', 'I', 7.5)
        self.set_text_color(*MUTED)
        self.cell(0, 5,
            'Generated by OrchestrAI | This is a quotation, not a tax invoice.',
            align='C')


def generate_quotation_pdf(
    quotation_number: str,
    customer_name: str,
    metal_type: str,
    weight_grams: float,
    design_code: str,
    rate_per_gram: float,
    making_charge_pct: float,
    making_charges: float,
    subtotal: float,
    gst_pct: float,
    gst_amount: float,
    total_amount: float,
    org_name: str = 'Baanganga Gold And Diamond (I) Ltd.',
    customer_city: str = '',
    valid_days: int = 3
) -> bytes:

    pdf = QuotationPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.set_margins(14, 14, 14)

    W = 182
    L = 14
    today = datetime.now()
    valid_until = today + timedelta(days=valid_days)

    # ── HEADER ────────────────────────────────────────
    # Company name
    pdf.set_xy(L, 14)
    pdf.set_font('Helvetica', 'B', 20)
    pdf.set_text_color(*BLUE)
    pdf.cell(100, 10, org_name, align='L')

    # QUOTATION badge (green for quotes, blue for invoices)
    pdf.set_fill_color(*GREEN)
    pdf.set_xy(142, 14)
    pdf.set_font('Helvetica', 'B', 12)
    pdf.set_text_color(*WHITE)
    pdf.cell(54, 10, 'QUOTATION', fill=True, align='C')

    # Tagline
    pdf.set_xy(L, 25)
    pdf.set_font('Helvetica', 'I', 8)
    pdf.set_text_color(*MUTED)
    pdf.cell(100, 4.5, 'Powered by OrchestrAI   |   Automate With AI', align='L')

    # Quote meta
    meta = [
        ('Quote No:', quotation_number),
        ('Date:', today.strftime('%d %b %Y')),
        ('Valid Until:', valid_until.strftime('%d %b %Y')),
    ]
    my = 25
    for label, value in meta:
        pdf.set_xy(142, my)
        pdf.set_font('Helvetica', '', 8.5)
        pdf.set_text_color(*MUTED)
        pdf.cell(28, 5, label, align='L')
        pdf.set_font('Helvetica', 'B', 8.5)
        pdf.set_text_color(*DARKTEXT)
        pdf.cell(26, 5, value, align='R')
        my += 5.5

    # Divider
    pdf.set_draw_color(*BLUE)
    pdf.set_line_width(0.8)
    pdf.line(L, 36, L + W, 36)
    pdf.set_line_width(0.2)
    pdf.set_draw_color(*BORDER)

    # ── CUSTOMER ──────────────────────────────────────
    y = 43
    pdf.set_xy(L, y)
    pdf.set_font('Helvetica', 'B', 7.5)
    pdf.set_text_color(*BLUE)
    pdf.cell(W, 4.5, 'QUOTATION FOR', align='L')

    y += 6
    pdf.set_xy(L, y)
    pdf.set_font('Helvetica', 'B', 13)
    pdf.set_text_color(*DARKTEXT)
    pdf.cell(W, 7, customer_name, align='L')

    if customer_city:
        y += 8
        pdf.set_xy(L, y)
        pdf.set_font('Helvetica', '', 8.5)
        pdf.set_text_color(*MUTED)
        pdf.cell(W, 5, customer_city, align='L')

    # ── ITEM DETAILS BOX ──────────────────────────────
    y += 10
    pdf.set_fill_color(*LIGHTBG)
    pdf.rect(L, y, W, 28, style='F')
    pdf.set_draw_color(*BLUE)
    pdf.set_line_width(0.5)
    pdf.rect(L, y, W, 28)
    pdf.set_line_width(0.2)

    pdf.set_xy(L + 4, y + 3)
    pdf.set_font('Helvetica', 'B', 8.5)
    pdf.set_text_color(*BLUE)
    pdf.cell(W - 8, 5, 'ITEM DETAILS', align='L')

    details = [
        ('Metal Type:', metal_type.upper(), 'Design Code:', design_code or 'Standard'),
        ('Weight:', f'{weight_grams:.3f} grams', 'Rate per gram:', f'Rs.{rate_per_gram:,.0f}'),
        ('Making Charges:', f'{making_charge_pct:.1f}% of metal value', '', ''),
    ]
    dy = y + 9
    for row in details:
        pdf.set_xy(L + 4, dy)
        pdf.set_font('Helvetica', '', 8)
        pdf.set_text_color(*MUTED)
        pdf.cell(30, 5, row[0], align='L')
        pdf.set_font('Helvetica', 'B', 8)
        pdf.set_text_color(*DARKTEXT)
        pdf.cell(55, 5, row[1], align='L')
        if row[2]:
            pdf.set_font('Helvetica', '', 8)
            pdf.set_text_color(*MUTED)
            pdf.cell(35, 5, row[2], align='L')
            pdf.set_font('Helvetica', 'B', 8)
            pdf.set_text_color(*DARKTEXT)
            pdf.cell(50, 5, row[3], align='L')
        dy += 6

    # ── PRICE BREAKDOWN TABLE ─────────────────────────
    y += 34
    # Header
    pdf.set_xy(L, y)
    pdf.set_fill_color(*BLUE)
    pdf.set_text_color(*WHITE)
    pdf.set_font('Helvetica', 'B', 8.5)
    pdf.cell(100, 8.5, 'Description', fill=True, align='L', border=0)
    pdf.cell(40, 8.5, 'Calculation', fill=True, align='R', border=0)
    pdf.cell(42, 8.5, 'Amount', fill=True, align='R', border=0)
    pdf.ln(8.5)

    # Rows
    metal_cost = weight_grams * rate_per_gram
    rows = [
        ('Metal Cost', f'{weight_grams:.3f}g × Rs.{rate_per_gram:,.0f}',
         f'Rs.{metal_cost:,.0f}', False),
        (f'Making Charges ({making_charge_pct:.0f}%)',
         f'{making_charge_pct:.0f}% of Rs.{metal_cost:,.0f}',
         f'Rs.{making_charges:,.0f}', True),
        ('Subtotal', '', f'Rs.{subtotal:,.0f}', False),
        (f'GST ({gst_pct:.0f}%)', f'{gst_pct:.0f}% of subtotal',
         f'Rs.{gst_amount:,.0f}', True),
    ]

    for desc, calc, amt, fill in rows:
        pdf.set_fill_color(*LIGHTBG) if fill else pdf.set_fill_color(*WHITE)
        pdf.set_text_color(*DARKTEXT)
        pdf.set_font('Helvetica', '', 8.5)
        pdf.cell(100, 7.5, desc, fill=True, align='L', border=0)
        pdf.set_text_color(*MUTED)
        pdf.cell(40, 7.5, calc, fill=True, align='R', border=0)
        pdf.set_text_color(*DARKTEXT)
        pdf.cell(42, 7.5, amt, fill=True, align='R', border=0)
        pdf.ln(7.5)

    # Total row
    pdf.set_fill_color(*BLUE)
    pdf.set_text_color(*WHITE)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(140, 9, 'TOTAL QUOTATION AMOUNT', fill=True, align='L', border=0)
    pdf.cell(42, 9, f'Rs.{total_amount:,.0f}', fill=True, align='R', border=0)
    pdf.ln(9)

    # ── AMOUNT IN WORDS ───────────────────────────────
    wy = pdf.get_y() + 6
    pdf.set_xy(L, wy)
    pdf.set_fill_color(*LIGHTBG)
    pdf.rect(L, wy, W, 9, style='F')
    pdf.set_draw_color(*GREEN)
    pdf.set_line_width(0.8)
    pdf.line(L, wy, L, wy + 9)
    pdf.set_line_width(0.2)
    pdf.set_xy(L + 3, wy + 2)
    pdf.set_font('Helvetica', '', 8)
    pdf.set_text_color(*MUTED)
    pdf.cell(38, 5, 'Amount in words:', align='L')
    pdf.set_font('Helvetica', 'B', 8)
    pdf.set_text_color(*DARKTEXT)
    pdf.cell(W - 41, 5, _amount_in_words(total_amount), align='L')

    # ── VALIDITY + NOTES ──────────────────────────────
    fy = wy + 16
    pdf.set_draw_color(*BORDER)
    pdf.line(L, fy, L + W, fy)

    pdf.set_xy(L, fy + 5)
    pdf.set_font('Helvetica', 'B', 7.5)
    pdf.set_text_color(*BLUE)
    pdf.cell(W, 4.5, 'Terms & Conditions:', align='L')
    pdf.ln(4.5)
    terms = [
        f'1. This quotation is valid for {valid_days} days from the date of issue.',
        '2. Gold rates are subject to market fluctuation. Final rate at time of order.',
        '3. Making charges may vary based on design complexity.',
        '4. GST @ ' + f'{gst_pct:.0f}% applicable as per government norms.',
        '5. Advance payment required to confirm order.',
    ]
    for t in terms:
        pdf.set_font('Helvetica', '', 7.5)
        pdf.set_text_color(*MUTED)
        pdf.cell(W, 4, t, align='L')
        pdf.ln(4)

    # Signature
    pdf.set_xy(140, fy + 5)
    pdf.set_font('Helvetica', '', 7.5)
    pdf.set_text_color(*MUTED)
    pdf.cell(56, 4, f'For  {org_name}', align='C')
    pdf.set_draw_color(*DARKTEXT)
    pdf.set_line_width(0.3)
    pdf.line(143, fy + 26, 195, fy + 26)
    pdf.set_xy(140, fy + 27)
    pdf.set_font('Helvetica', '', 7.5)
    pdf.set_text_color(*MUTED)
    pdf.cell(56, 4, 'Authorised Signatory', align='C')

    return bytes(pdf.output())
