-- Migration: Create quotations table
-- Stores quotation records generated by the quotation adapter

CREATE TABLE IF NOT EXISTS quotations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id UUID NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
    quotation_number VARCHAR(50) NOT NULL UNIQUE,
    customer_id UUID REFERENCES customers(id) ON DELETE SET NULL,
    customer_name VARCHAR(255) NOT NULL,
    metal_type VARCHAR(20) NOT NULL,
    weight_grams NUMERIC(10,3) NOT NULL,
    design_code VARCHAR(50),
    rate_per_gram NUMERIC(12,2) NOT NULL,
    making_charge_pct NUMERIC(5,2) NOT NULL,
    making_charges NUMERIC(12,2) NOT NULL,
    subtotal NUMERIC(12,2) NOT NULL,
    gst_pct NUMERIC(5,2) NOT NULL,
    gst_amount NUMERIC(12,2) NOT NULL,
    total_amount NUMERIC(12,2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'sent',
    valid_until DATE NOT NULL,
    created_by UUID REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_quotations_org ON quotations(org_id);
CREATE INDEX IF NOT EXISTS idx_quotations_customer ON quotations(customer_id);
CREATE INDEX IF NOT EXISTS idx_quotations_status ON quotations(status);
CREATE INDEX IF NOT EXISTS idx_quotations_valid_until ON quotations(valid_until);
