UPDATE workflows SET description = $j$Turns a case number (any format) into the case, so later steps can use it.$j$, steps = $j$[{"op": "resolve_entity", "params": {"table": "cases", "into": "case", "name_from": "$fields.case_number", "match_column": "case_number", "normalize": "identifier", "expose": {"resolved_case_number": "case_number"}}}]$j$::jsonb, entity_schema = $j${"case_number": {"type": "string", "required": true, "description": "The case number, for example CS-26-08-00017. Any format is accepted."}}$j$::jsonb WHERE intent_key = 'case_find';
UPDATE workflows SET description = $j$Sends the person who raised the case a message, unless they are the one acting. Give it tell_prefix and tell_text, for example 'is now with' and a name.$j$, steps = $j$[{"op": "resolve_entity", "when": {"field": "$case.complainant_id", "exists": true}, "params": {"table": "users", "into": "requester", "name_from": "$case.complainant_id", "match_column": "id"}}, {"op": "notify.user", "when": {"and": [{"field": "$requester.phone", "exists": true}, {"field": "$requester.phone", "not_equals": "$user.phone"}]}, "params": {"to": "$requester.phone", "message_template": "ℹ️ Case {case_case_number} ({case_title}) {tell_prefix} {tell_text}"}}]$j$::jsonb, entity_schema = $j${"tell_prefix": {"type": "string", "required": true, "description": "The words after the case number and title, for example 'is now with'."}, "tell_text": {"type": "string", "required": true, "description": "The rest of the message, for example a person's name or a closing note."}}$j$::jsonb WHERE intent_key = 'case_tell_requester';
INSERT INTO workflows (org_id, intent_key, name, description, workflow_type, steps, entity_schema, gates, training_phrases, version, is_active, menu_section, kind)
SELECT o.id, 'case_tell_handler', $j$Tell the person who has the case$j$, $j$Sends the person the case is with now a message, unless they are the one acting. Give it tell_prefix and tell_text.$j$, 'action', $j$[{"op": "resolve_entity", "when": {"field": "$case.assigned_to_id", "exists": true}, "params": {"table": "users", "into": "handler", "name_from": "$case.assigned_to_id", "match_column": "id"}}, {"op": "notify.user", "when": {"and": [{"field": "$handler.phone", "exists": true}, {"field": "$handler.phone", "not_equals": "$user.phone"}, {"field": "$handler.phone", "not_equals": "$requester.phone"}]}, "params": {"to": "$handler.phone", "message_template": "ℹ️ Case {case_case_number} ({case_title}) {tell_prefix} {tell_text}"}}]$j$::jsonb, $j${"tell_prefix": {"type": "string", "required": true, "description": "The words after the case number and title, for example 'was closed.'"}, "tell_text": {"type": "string", "required": true, "description": "The rest of the message, for example a closing note."}}$j$::jsonb, '[]'::jsonb, '[]'::jsonb, 1, true, 'other', 'block'
  FROM orgs o WHERE o.slug = 'godrej-emerald' ON CONFLICT (org_id, intent_key) DO NOTHING;
UPDATE workflows SET name = $j$Assign a case$j$, description = $j$Gives a case to one person, keeps an optional note, and tells them and whoever raised it.$j$, kind = 'workflow', steps = $j$[{"op": "run_workflow", "params": {"workflow": "case_find"}}, {"op": "run_workflow", "params": {"workflow": "case_assign"}}, {"op": "run_workflow", "when": {"field": "$fields.comment_text", "exists": true}, "params": {"workflow": "case_comment"}}, {"op": "run_workflow", "params": {"workflow": "case_tell_assignee"}}, {"op": "run_workflow", "params": {"workflow": "case_tell_requester", "inputs": {"tell_prefix": "is now with", "tell_text": "$assignee.name"}}}]$j$::jsonb, entity_schema = $j${"case_number": {"type": "string", "required": true, "description": "The case number, for example CS-26-08-00017. Any format is accepted."}, "assignee_name": {"type": "string", "required": true, "description": "Who the case goes to. If the person says me or myself, use the person's own name."}, "comment_text": {"type": "string", "required": false, "description": "An optional note for them."}}$j$::jsonb, training_phrases = $j$["assign {case_number} to {name}", "give case {case_number} to {name}", "hand this case over to {name}", "assign this case to myself", "pass {case_number} on to {name}"]$j$::jsonb, response_template = $j$✅ Case {resolved_case_number} is now with {assignee_name}.$j$, command_description = $j$Assign a case to someone$j$, menu_section = 'other' WHERE intent_key = 'case_pass_on';
UPDATE workflows SET name = $j$Add an update to a case$j$, description = $j$Adds a note to a case and tells the person who has it and the person who raised it.$j$, kind = 'workflow', steps = $j$[{"op": "run_workflow", "params": {"workflow": "case_find"}}, {"op": "run_workflow", "params": {"workflow": "case_comment"}}, {"op": "run_workflow", "params": {"workflow": "case_tell_requester", "inputs": {"tell_prefix": "has a new update:", "tell_text": "$fields.comment_text"}}}, {"op": "run_workflow", "params": {"workflow": "case_tell_handler", "inputs": {"tell_prefix": "has a new update:", "tell_text": "$fields.comment_text"}}}]$j$::jsonb, entity_schema = $j${"case_number": {"type": "string", "required": true, "description": "The case number, for example CS-26-08-00017. Any format is accepted."}, "comment_text": {"type": "string", "required": true, "description": "The note to add."}}$j$::jsonb, training_phrases = $j$["comment on {case_number}", "add an update to {case_number}", "add a note to case {case_number}", "update case {case_number}", "write a remark on {case_number}"]$j$::jsonb, response_template = $j$✅ Update added to case {resolved_case_number}.$j$, command_description = $j$Add a note to a case$j$, menu_section = 'other' WHERE intent_key = 'case_add_update';
UPDATE workflows SET name = $j$Close a case with a note$j$, description = $j$Closes a case. The closing note is compulsory. Tells the person who has it and the person who raised it.$j$, kind = 'workflow', steps = $j$[{"op": "run_workflow", "params": {"workflow": "case_find"}}, {"op": "run_workflow", "params": {"workflow": "case_close", "inputs": {"note": "$fields.comment_text"}}}, {"op": "run_workflow", "params": {"workflow": "case_tell_requester", "inputs": {"tell_prefix": "was closed. Closing note:", "tell_text": "$fields.comment_text"}}}, {"op": "run_workflow", "params": {"workflow": "case_tell_handler", "inputs": {"tell_prefix": "was closed. Closing note:", "tell_text": "$fields.comment_text"}}}]$j$::jsonb, entity_schema = $j${"case_number": {"type": "string", "required": true, "description": "The case number, for example CS-26-08-00017. Any format is accepted."}, "comment_text": {"type": "string", "required": true, "description": "The closing note, so everyone knows what was done. Compulsory."}}$j$::jsonb, training_phrases = $j$["close {case_number}", "resolve {case_number}", "mark {case_number} as closed", "the issue in {case_number} is fixed", "close case {case_number} with a note"]$j$::jsonb, response_template = $j$✅ Case {resolved_case_number} closed.$j$, command_description = $j$Close a case with a closing note$j$, menu_section = 'other' WHERE intent_key = 'case_close_with_note';
INSERT INTO workflows (org_id, intent_key, name, description, workflow_type, steps, entity_schema, gates, training_phrases, response_template, command_description, version, is_active, menu_section, kind)
SELECT o.id, 'file_a_complaint', $j$File a complaint$j$, $j$Files a new complaint for the resident. The due time comes from the priority.$j$, 'action', $j$[{"op": "run_workflow", "params": {"workflow": "case_create"}}, {"op": "notify.whatsapp", "params": {"attach_pdf": false}}]$j$::jsonb, $j${"title": {"type": "string", "required": true, "description": "Short summary of the complaint, e.g. \"Water leakage in Wing 2 basement\""}, "location": {"type": "string", "required": true, "description": "Wing / flat / common area where the issue is"}, "priority": {"type": "string", "required": true, "description": "One of urgent, high, medium, low. ONLY set this if the user explicitly states an urgency level or uses clearly urgent language (for example emergency, immediately dangerous, fire). Never infer priority from the topic of the complaint alone. If not stated, leave it unset and ask the user, or default to medium only after telling them you are defaulting it.", "enum": ["urgent", "high", "medium", "low"]}, "description": {"type": "string", "required": false, "description": "Optional longer explanation of the issue"}}$j$::jsonb, '[]'::jsonb, $j$["register a complaint", "file a complaint", "report an issue", "file a case", "new complaint about {title}", "book a complaint"]$j$::jsonb, $j$✅ *Complaint Registered*

Case #: *{case_number}*
Title: {title}
Status: reported

_Your complaint has been recorded._$j$, $j$File a new complaint or case$j$, 1, false, 'create', 'workflow'
  FROM orgs o WHERE o.slug = 'godrej-emerald' ON CONFLICT (org_id, intent_key) DO NOTHING;
SELECT intent_key, kind, is_active FROM workflows ORDER BY kind, intent_key;
